name: Android Play Store Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+(-RC[0-9]+)?'
    branches:
      - manuel/new-version-code-schema

jobs:
  deploy:
    name: Deploying to Play Store
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ðŸ›Ž
        uses: actions/checkout@v2

      - name: Setup JDK 11 ðŸ”§
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: 11

      - name: Setup Android SDK ðŸ”§
        uses: android-actions/setup-android@v2

      - name: Setup ruby ðŸ”§
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Setup Node.js ðŸ”§
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: 'yarn'
          cache-dependency-path: |
            yarn.lock

      - name: Caching Gradle packages ðŸ”¨
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Caching ruby dependencies ðŸ”¨
        uses: actions/cache@v2
        with:
          path: 'vendor/bundle'
          key: ${{ runner.os }}-gems-${{ secrets.GEMS_CACHE_VERSION }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies ðŸ”¨
        run: |
          yarn install
          bundle install

      - name: Build and deploy on Play Store ðŸš€
        run: bundle exec fastlane android deploy_to_internal_testing
        env:
          VERSION_OVERRIDE: 1.2.0
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
          ANDROID_SIGNING_ALIAS: ${{ secrets.ANDROID_SIGNING_ALIAS }}
          ANDROID_SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
          PLAYSTORE_JSON_KEY: ${{ secrets.PLAYSTORE_JSON_KEY }}
